### ISSUE TITLE
sending and receiving data not used

### ISSUE THREAD

**Issue by HiroKoni** [tsukurobo/cubic_arduino#3]
@shohkoba 
プログラムで全く使わないモータやエンコーダのデータを送受信する必要はないのでは、と思ったのですがどうでしょう？
実装は面倒そうですが

**Comment by shohkoba** [comment]
確かにそうだよね．
ただ，毎回同じだけのデータを送受信すると，ループ周期が一定になりやすいのではという考えのもとに設計したんだよね．
今はいいかんじに動いてるから，何か問題があるときに必要に応じて直すのでもいいと思ってる．

**Comment by HiroKoni** [comment]
なるほど
